### ISSUE TITLE
最终代码跑出的结果

### ISSUE THREAD

**Issue by JittorAD** [ForeverFancy/VectorNet#1]
请问您在Argoverse的eval和test set上跑的ADE/FDE是多少呢？多谢

**Comment by ForeverFancy** [comment]
> 请问您在Argoverse的eval和test set上跑的ADE/FDE是多少呢？多谢

你好，由于代码只是一个 demo，我并没有使用全量数据集进行训练（并且代码可能存在一些问题，不打算再维护了），具体 performance 可以参考论文，谢谢。
